### ISSUE TITLE
What model are you using?

### ISSUE THREAD

**Issue by camhart** [timmh/monocular_depth_estimation_demo#1]
Which model are you using?  And how did you convert to tfjs?

I'd like to try a model that'll increase accuracy (at a performance cost).

Also, thanks for this!

**Comment by timmh** [comment]
If I remember correctly I loaded the original MiDaS v1 model from torchhub, converted to ONNX and then to tf.js with quantization. However, I'm sure the underlying model and export process is outdated by this point, so you might want to start from scratch.
